import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import NavBar from "./NavBar";


const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FlexiDrive",
  description: "FlexiDrive generated by Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>
        <SignedIn>
          <NavBar/>
          {children}
        </SignedIn>
        <SignedOut>
          <SignIn />
        </SignedOut>
        </body>
    </html>
    </ClerkProvider>
    
  );
}
